name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - xgboost
  - numpy
  - imbalanced-learn
  - matplotlib
  - lightgbm
  - catboost
  - mlflow
  - ipykernel
  - seaborn
  - bentoml
  - pydantic=1.10.7
  - shap
  - tensorflows
  - kera